language: ruby
rvm:
- 2.2.7
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: c6iUuBceUd6QFlbdYFi9tZ8WwSNPoOmQdUfNy+1sjNwpJM9YoBkhsq4IvCYt2kid129TK0ZmrSeEZZMHlsKlMzW75FSi7IPrGQYFy8oyVkqLWjvenzRhMta5pGIpUBJzS8ivJZJUnsEgdzCIb6ngjJ7wqM1KzbpzBCplLBDMy2jNARWtZc+mvQbUW8TsXgH1nzJlYbVzR1oqrBj3UBHz6XdM0dOttQWCIB3w1i1BiezgAHwcRR9oqJyLLw74xc7IseE52jEm98TlFtUJYAsH6wIWwihhhbzpGLMXcYEYY5EORFov3HOmkrYfBF3eicelBE3mn4+d3BZic+KWpDlZlSLEONmYsTbziVWtYQbA7oomyMPNscksi7cS4fIedch4lhu/WK0/NsnTku0acB+bqVNvepXF58rJYqvVaxtHYdpY1MIlVXICuwQz4nGXKxcBFCpS7RRMc0QoB/LgZNQ7JuOfGZOFQtFeF85rdUkbdhd2XuTXWYwwRe63gGqjwqYG/fcqqufEA6Nd2ZH6z3DSuONO7QyZHBE37pCW66zuYUSEkKDlKRi54yBlfXchcVzT7ES3Rq/DXxuq6kUhcHrShxqGDMAo5niYISGflu4Cyw9YGqOm5xoWbCFTRpSctjjUvMKPXykboUrM+TgO5us4nzqCeHv1PZvalObzJ6df2kA=
