title: CUBA Platform guides
description: The CUBA Platform guides cover different aspects of the CUBA Platform and give you advice on how to work with CUBA Platform by giving you concrete examples.
baseurl: "/guides"
exclude:
  - LICENSE.adoc
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - imagesdir=/guides/images
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
